services:
  - type: web
    name: binance-alert-bot
    runtime: python
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    pythonVersion: 3.12.6   # 👈 must be aligned with startCommand
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: PORT
        value: 5000
